### ISSUE TITLE
make fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [LLNL/UnifyFS#609] opened 2021-03-09 16:56 UTC
[jw@cn06 unifyfs]$ make VERBOSE=1 -j1
make  all-recursive
make[1]: Entering directory '/data/jw/unifyfs'
Making all in meta
make[2]: Entering directory '/data/jw/unifyfs/meta'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/meta/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/jw/unifyfs/meta/src'
make[3]: Entering directory '/data/jw/unifyfs/meta'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/jw/unifyfs/meta'
make[2]: Leaving directory '/data/jw/unifyfs/meta'
Making all in server
make[2]: Entering directory '/data/jw/unifyfs/server'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/server/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/jw/unifyfs/server/src'
make[3]: Entering directory '/data/jw/unifyfs/server'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/jw/unifyfs/server'
make[2]: Leaving directory '/data/jw/unifyfs/server'
Making all in client
make[2]: Entering directory '/data/jw/unifyfs/client'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/client/src'
  CC       libunifyfs_la-unifyfs.lo
unifyfs.c: In function 'unifyfs_fid_create_file':
unifyfs.c:927:5: error: 'strncpy' specified bound 1024 equals destination size [-Werror=stringop-truncation]
  927 |     strncpy((void*)&unifyfs_filelist[fid].filename, path, UNIFYFS_MAX_FILENAME);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:996: libunifyfs_la-unifyfs.lo] Error 1
make[3]: Leaving directory '/data/jw/unifyfs/client/src'
make[2]: *** [Makefile:470: all-recursive] Error 1
make[2]: Leaving directory '/data/jw/unifyfs/client'
make[1]: *** [Makefile:498: all-recursive] Error 1
make[1]: Leaving directory '/data/jw/unifyfs'
make: *** [Makefile:409: all] Error 2
[jw@cn06 unifyfs]$

**Comment by CamStan** [comment] 2021-03-09 17:58
I believe I already have a branch that fixes this (along with a few other things). Should be merging it this week.

**Comment by LutzWeischerFujitsu** [comment] 2021-03-22 11:26
Is it merged? I still get this error.

**Comment by CamStan** [comment] 2021-03-22 19:28
Just got merged. Let me know if you're still running into this issue.

**Comment by LutzWeischerFujitsu** [comment] 2021-03-23 08:28
Not yet. make reports: 
... 
make[3]: *** [Makefile:1419: sysio-open-gotcha] Error 1
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
/usr/bin/ld: sysio_open_static-sysio-open.o: in function `dump_stat':
/data/jw/unifyfs/examples/src/testlib.h:221: undefined reference to `major'
/usr/bin/ld: /data/jw/unifyfs/examples/src/testlib.h:221: undefined reference to `minor'
/usr/bin/ld: /data/jw/unifyfs/examples/src/testlib.h:242: undefined reference to `major'
/usr/bin/ld: /data/jw/unifyfs/examples/src/testlib.h:242: undefined reference to `minor'
/usr/bin/ld: ../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1423: sysio-open-static] Error 1
make[3]: Leaving directory '/data/jw/unifyfs/examples/src'
make[2]: *** [Makefile:398: all-recursive] Error 1
make[2]: Leaving directory '/data/jw/unifyfs/examples'
make[1]: *** [Makefile:498: all-recursive] Error 1
make[1]: Leaving directory '/data/jw/unifyfs'
make: *** [Makefile:409: all] Error 2
(base) [jw@cn06 unifyfs]$ clear
(base) [jw@cn06 unifyfs]$ (base) [jw@cn06 unifyfs]$ make VERBOSE=1 -j1
make  all-recursive
make[1]: Entering directory '/data/jw/unifyfs'
Making all in meta
make[2]: Entering directory '/data/jw/unifyfs/meta'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/meta/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/jw/unifyfs/meta/src'
make[3]: Entering directory '/data/jw/unifyfs/meta'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/jw/unifyfs/meta'
make[2]: Leaving directory '/data/jw/unifyfs/meta'
Making all in server
make[2]: Entering directory '/data/jw/unifyfs/server'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/server/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/jw/unifyfs/server/src'
make[3]: Entering directory '/data/jw/unifyfs/server'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/jw/unifyfs/server'
make[2]: Leaving directory '/data/jw/unifyfs/server'
Making all in client
make[2]: Entering directory '/data/jw/unifyfs/client'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/client/src'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/data/jw/unifyfs/client/src'
make[3]: Entering directory '/data/jw/unifyfs/client'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/jw/unifyfs/client'
make[2]: Leaving directory '/data/jw/unifyfs/client'
Making all in examples
make[2]: Entering directory '/data/jw/unifyfs/examples'
Making all in src
make[3]: Entering directory '/data/jw/unifyfs/examples/src'
  CCLD     cr-posix
/usr/bin/ld: cannot find -lspath
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1351: cr-posix] Error 1
make[3]: Leaving directory '/data/jw/unifyfs/examples/src'
make[2]: *** [Makefile:398: all-recursive] Error 1
make[2]: Leaving directory '/data/jw/unifyfs/examples'
make[1]: *** [Makefile:498: all-recursive] Error 1
make[1]: Leaving directory '/data/jw/unifyfs'
make: *** [Makefile:409: all] Error 2
(base) [jw@cn06 unifyfs]$

**Comment by adammoody** [comment] 2021-03-23 17:19
The error in this case looks to be tripping on our use of ``major()`` and ``minor()``:

https://github.com/LLNL/UnifyFS/blob/a914fe3b0569e593186bd8698465151ddc779e22/examples/src/testlib.h#L221

Reference:  https://linux.die.net/man/3/major

**Comment by CamStan** [comment] 2021-03-23 18:18
Well, I think I've just confused myself at this point, so here's what I'm seeing so far.

I haven't been able to reproduce this, but from looking up other projects that have run into this, it looks like on newer glibc (starting at 2.25 I think) the `major()` and `minor()` macros are removed from `sys/types.h` and are only available in `sys/sysmacros.h`.
Announcement here: https://sourceware.org/legacy-ml/libc-alpha/2015-11/msg00253.html

However, it also seems `sys/sysmacros.h` is a non-standard header and might not always be available. So may need to also include `AC_HEADER_MAJOR` (https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Headers.html) in our _configure.ac_.

However, some additional things might need to be done in addition to adding`AC_HEADER_MAJOR` since depending on the versions of things such as gcc, glibc, Red Hat, Slurm, and autoconf, who defines these macros first or at all could cause other problems.
https://bugs.schedmd.com/show_bug.cgi?id=3982
and 
https://lists.gnu.org/archive/html/autoconf-patches/2016-09/msg00008.html

I also may have just gone down the wrong rabbit hole here.

**Comment by rgmiller** [comment] 2021-04-19 15:16
Just to add another data point:  I see this same issue with `major()` and `minor()` on Ubuntu 20.04LTS and CentOS 8.3.

Interestingly, I only see the problem when I try to build using the autotools; the spack package builds successfully on both platforms.  (I haven't yet figured out what spack is doing differently.)

**Comment by CamStan** [comment] 2021-04-27 19:19
Closing as original issue this was opened for I believe has been resolved and a new issue was made to continue `major()` and `minor()` discussion.

**Closed by CamStan** 2021-04-27 19:19 UTC
