### ISSUE TITLE
Update Mochi stack dependencies to later versions

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#584] opened 2020-12-03 23:02 UTC
We currently depend on Margo v0.4.3 and Mercury v1.0.1 which are a bit behind their latest versions (v0.9 and v2.0.0 respectively).

Initially ran into this in issue #573 as spackages changed.

It'll be better for us to be on newer software now that we're trying to scale up and debug performance issues and deadlocks that we may get stuck on.

The Mochi team suggested we reach out when we're ready to update. They stated:
> The [Margo] API changes are very minor but I'm not sure which ones you might bump into. There are some nice internal improvements in Margo to look forward to once you do, though, including some performance improvements (in conjunction with the newer Mercury especially), ability to profile RPCs, ability to set/inspect configuration via json, and some other odds and ends.

**Comment by sandrain** [comment] 2020-12-14 18:21
@CamStan I've tested with mercury-2.0.0 and margo-0.9, and it seems like unifyfs runs fine when using bmi+tcp. It failed with ofi+tcp. My test was on Summit without using spack.

**Comment by sandrain** [comment] 2020-12-14 21:33
It seems like changing protocol from ```ofi+tcp://``` to ```ofi+sockets://``` makes unifyfs runs fine with new mercury, at least in my testing environment on Summit:

```
diff --git a/server/src/margo_server.c b/server/src/margo_server.c
index 36e74cb..2cdc438 100644
--- a/server/src/margo_server.c
+++ b/server/src/margo_server.c
@@ -41,7 +41,7 @@ static const char* PROTOCOL_MARGO_SHM   = "na+sm://";
 static const char* PROTOCOL_MARGO_TCP = "bmi+tcp://";
 static const char* PROTOCOL_MARGO_RMA = "bmi+tcp://";
 #elif defined(NA_HAS_OFI)
-static const char* PROTOCOL_MARGO_TCP = "ofi+tcp://";
+static const char* PROTOCOL_MARGO_TCP = "ofi+sockets://";
 static const char* PROTOCOL_MARGO_RMA = "ofi+verbs://";
 #else
 #error No supported Mercury NA plugin found (please use one of: 'BMI', 'OFI')
```

In the previous mercury (v1.0.1), the ```ofi+tcp://``` is transformed to ```ofi+sockets://```:

https://github.com/mercury-hpc/mercury/blob/0de22781cd08931416aba8050c5a6647c23abcb9/src/na/na_ofi.c#L127

but in v2.0, ```ofi+tcp://``` becomes ```tcp;ofi+rxm://```

https://github.com/mercury-hpc/mercury/blob/5f85369c39ba20a89b00d60978c80bbaf74f12eb/src/na/na_ofi.c#L118

I didn't use spack but used the following bootstrap script:

```
#!/bin/bash
#
# This is an easy-bake script to download and build all UnifyFS's dependencies.
#

ROOT="$(pwd)"

mkdir -p deps
mkdir -p install
INSTALL_DIR=$ROOT/install

cd deps

repos=( https://xgitlab.cels.anl.gov/sds/bmi.git
        https://github.com/LLNL/GOTCHA.git
        https://github.com/pmodels/argobots.git
        https://github.com/mercury-hpc/mercury.git
        https://xgitlab.cels.anl.gov/sds/margo.git
        https://github.com/json-c/json-c.git
        https://github.com/pmodels/openpa.git
)


if [ "$1" = "--with-leveldb" ] ; then
    repos+=(https://github.com/google/leveldb.git)
fi

for i in "${repos[@]}" ; do
        # Get just the name of the project (like "mercury")
        name=$(basename $i | sed 's/\.git//g')
        if [ -d $name ] ; then
                echo "$name already exists, skipping it"
        else
                if [ "$name" == "mercury" ] ; then
                        git clone --recurse-submodules $i
                else
                        git clone $i
                fi
        fi
done

echo "### building openpa ###"
cd openpa
git clean -fdx
git checkout v1.0.4
./autogen.sh
mkdir -p build
cd build
../configure --prefix="$INSTALL_DIR"
make -j $(nproc) && make install
cd ../..

#echo "### building bmi ###"
#cd bmi
#./prepare && ./configure --enable-shared --enable-bmi-only \
#       --prefix="$INSTALL_DIR"
#make -j $(nproc) && make install
#cd ..

if [ "$1" = "--with-leveldb" ] ; then
    echo "### building leveldb ###"
    cd leveldb
    git checkout 1.22
    mkdir -p build && cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
        -DBUILD_SHARED_LIBS=yes ..
    make -j $(nproc) && make install
    cd ..
    cd ..
else
    echo "### skipping leveldb build ###"
fi

echo "### building GOTCHA ###"
cd GOTCHA
# Unify won't build against latest GOTCHA, so use a known compatible version.
git checkout 1.0.3
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ..
make -j $(nproc) && make install
cd ..
cd ..

echo "### building argobots ###"
cd argobots
git checkout v1.0
./autogen.sh && CC=gcc ./configure --prefix="$INSTALL_DIR"
make -j $(nproc) && make install
cd ..

echo "### building json-c ###"
cd json-c
git checkout json-c-0.15-20200726
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ..
make -j $(nproc) && make install
cd ..
cd ..

echo "### building mercury ###"
cd mercury
git checkout v2.0.0
git submodule update --init
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
      -DMERCURY_USE_SELF_FORWARD=ON \
      -DMERCURY_USE_BOOST_PP=ON \
      -DMERCURY_USE_CHECKSUMS=ON \
      -DMERCURY_USE_EAGER_BULK=ON \
      -DMERCURY_USE_SYSTEM_MCHECKSUM=OFF \
      -DNA_USE_BMI=OFF \
      -DNA_USE_OFI=ON \
      -DMERCURY_USE_XDR=OFF \
      -DBUILD_SHARED_LIBS=ON ..

make -j $(nproc) && make install
cd ..
cd ..

echo "### building margo ###"
cd margo
git checkout v0.9
export PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig:$INSTALL_DIR/lib64/pkgconfig"
./prepare.sh
./configure --prefix="$INSTALL_DIR" --enable-shared
make -j $(nproc) && make install
cd ..

cd "$ROOT"

echo "*************************************************************************"
echo "Dependencies are all built.  You can now build UnifyFS with:"
echo ""
echo -n "  export PKG_CONFIG_PATH=$INSTALL_DIR/lib/pkgconfig && "
echo "export LEVELDB_ROOT=$INSTALL_DIR"
echo -n "  ./autogen.sh && ./configure --with-gotcha=$INSTALL_DIR"
echo " --prefix=$INSTALL_DIR"
echo "  make"
echo ""
echo "*************************************************************************"
```

Other system modules:

```
module load gcc/6.4.0
module load cmake/3.18.2
module load libfabric/1.7.0
```

In addition, we probably want to have a option (using the ```configurator```) to choose the protocol (bmi or ofi), because mercury can be built with both bmi and ofi. When both are available, currently bmi will be selected (over ofi).

**Comment by sandrain** [comment] 2020-12-15 00:34
I've deleted my previous message, because it turned out that my environment was kinda broken. Specifically, I was working with a wrong libfabric build. Anyway, I've tested again, and it seems like both bmi+tcp and ofi+tcp work fine on Summit. I've tested with mercury-v2.0.0 and margo-v0.9. 

@CamStan I didn't use spack, and here is my (modified) bootstrap.sh (added json-c and libfabric):

```
#!/bin/bash
#
# This is an easy-bake script to download and build all UnifyFS's dependencies.
#

#source env.sh

module load gcc/6.4.0
module load cmake/3.18.2

ROOT="$(pwd)"

mkdir -p deps
mkdir -p install
INSTALL_DIR=$ROOT/install

rm -rf $INSTALL_DIR/*

cd deps

repos=( https://xgitlab.cels.anl.gov/sds/bmi.git
        https://github.com/LLNL/GOTCHA.git
        https://github.com/pmodels/argobots.git
        https://github.com/mercury-hpc/mercury.git
        https://xgitlab.cels.anl.gov/sds/margo.git
        https://github.com/json-c/json-c.git
        https://github.com/pmodels/openpa.git
        https://github.com/ofiwg/libfabric.git
)


if [ "$1" = "--with-leveldb" ] ; then
    repos+=(https://github.com/google/leveldb.git)
fi

for i in "${repos[@]}" ; do
        # Get just the name of the project (like "mercury")
        name=$(basename $i | sed 's/\.git//g')
        if [ -d $name ] ; then
                echo "$name already exists, skipping it"
        else
                if [ "$name" == "mercury" ] ; then
                        git clone --recurse-submodules $i
                else
                        git clone $i
                fi
        fi
done

echo "### building openpa ###"
cd openpa
git clean -fdx
git checkout v1.0.4
./autogen.sh
mkdir -p build
cd build
../configure --prefix="$INSTALL_DIR"
make -j $(nproc) && make install
cd ../..

echo "### building bmi ###"
cd bmi
./prepare && ./configure --enable-shared --enable-bmi-only \
        --prefix="$INSTALL_DIR"
make -j $(nproc) && make install
cd ..

if [ "$1" = "--with-leveldb" ] ; then
    echo "### building leveldb ###"
    cd leveldb
    git checkout 1.22
    mkdir -p build && cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
        -DBUILD_SHARED_LIBS=yes ..
    make -j $(nproc) && make install
    cd ..
    cd ..
else
    echo "### skipping leveldb build ###"
fi

echo "### building GOTCHA ###"
cd GOTCHA
# Unify won't build against latest GOTCHA, so use a known compatible version.
git checkout 1.0.3
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ..
make -j $(nproc) && make install
cd ..
cd ..

echo "### building argobots ###"
cd argobots
git checkout v1.0
./autogen.sh && CC=gcc ./configure --prefix="$INSTALL_DIR"
make -j $(nproc) && make install
cd ..

echo "### building json-c ###"
cd json-c
git checkout json-c-0.15-20200726
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" ..
make -j $(nproc) && make install
cd ..
cd ..

echo "### building libfabric ###"
cd libfabric
git clean -fdx
git checkout v1.11.1
./autogen.sh
mkdir -p build
cd build
../configure --prefix="$INSTALL_DIR" \
             --enable-sockets --enable-rxm --enable-verbs --enable-tcp
make -j $(nproc) && make install
cd ../..

export LD_LIBRARY_PATH=$INSTALL_DIR/lib:$INSTALL_DIR/lib64
export PKG_CONFIG_PATH=$INSTALL_DIR/lib/pkgconfig:$INSTALL_DIR/lib64/pkgconfig

echo "### building mercury ###"
cd mercury
git clean -fdx
git checkout v2.0.0
git submodule update --init
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
      -DMERCURY_USE_SELF_FORWARD=ON \
      -DMERCURY_USE_BOOST_PP=ON \
      -DMERCURY_USE_CHECKSUMS=ON \
      -DMERCURY_USE_EAGER_BULK=ON \
      -DMERCURY_USE_SYSTEM_MCHECKSUM=OFF \
      -DNA_USE_BMI=ON \
      -DNA_USE_OFI=ON \
      -DMERCURY_USE_XDR=OFF \
      -DBUILD_SHARED_LIBS=ON ..

make -j $(nproc) && make install
cd ..
cd ..

echo "### building margo ###"
cd margo
git checkout v0.9
./prepare.sh
./configure --prefix="$INSTALL_DIR" --enable-shared
make -j $(nproc) && make install
cd ..

cd "$ROOT"

echo "*************************************************************************"
echo "Dependencies are all built.  You can now build UnifyFS with:"
echo ""
echo -n "  export PKG_CONFIG_PATH=$INSTALL_DIR/lib/pkgconfig && "
echo "export LEVELDB_ROOT=$INSTALL_DIR"
echo -n "  ./autogen.sh && ./configure --with-gotcha=$INSTALL_DIR"
echo " --prefix=$INSTALL_DIR"
echo "  make"
echo ""
echo "*************************************************************************"
```

And, as @MichaelBrim mentioned, we do not need to have a separate mercury build for each protocol. Also, there seems to be a difference between mercury-v2 and mercury-v1 in handling the address string `ofi+tcp`. mercury-v1 converted `ofi+tcp` to `sockets` while mercury-v2 converts it to `tcp;ofi+rxm`, so different provider is used in libfabfic.

**Comment by CamStan** [comment] 2020-12-15 19:31
Nice! Thank you @sandrain! I'll try this over here and test again with Spack as well.

Any particular reason for these versions of `gcc` and `cmake`? Is there a min requirement for any of the dependencies, or are these just what you happened to test with?
```
module load gcc/6.4.0
module load cmake/3.18.2
```

**Comment by sandrain** [comment] 2020-12-15 20:17
@CamStan The new version of Margo was complaining when using gcc-4.8.x. (c99 related).

**Comment by carns** [comment] 2021-02-01 18:58
FYI, the updated mochi package has landed upstream in spack now, see https://github.com/spack/spack/pull/20273.

(and please switch to the "mochi-margo" name now when you have a chance; the "margo" package continues to work but will be deprecated eventually)

Per some other comments above:
* You can still get the sockets provider if you prefer in Mercury 2.0, but you have to explicitly use the "sockets://" URI type now.  As you've noted its switched over to the tcp provider by default otherwise.
* Give me a yell (or post on mochi-devel, or open an issue on our gitlab) if you spot any margo build problems like the gcc 4.x thing.  There was recently a fix in Argobots for gcc 4.x, but this might be something different.

**Comment by MichaelBrim** [comment] 2021-02-01 19:52
I have been trying to get a working configuration of UnifyFS using mochi-margo (from sds-repo spack repo) in my Ubuntu docker container. For some reason, only the "ofi+sockets" URI worked for me when passed to margo_init(). I tried "ofi+tcp" and "tcp", but both failed to initialize.

I'm also unable to initialize with "na+sm", which was working just fine before with margo 0.4.3 and mercury 1.0.1. The weird thing is that if I just use the example server code from https://mochi.readthedocs.io/en/latest/margo/01_init.html and use the same settings as we do in Unify for the progress thread (1) and pool size (4), I can initialize with "na+sm" in that simple program. For some reason, the same exact call fails in the UnifyFS server.

@carns I can share my Dockerfile if that is useful to you to help debug either of these problems.

**Comment by carns** [comment] 2021-02-02 21:54
@MichaelBrim on the first issue, the tcp provider will only work with Mercury if the rxm provider is also available (kind of like how verbs works with mercury, they both use rxm for some shared functionality).  So make sure that the libfabric package has `fabrics=sockets,tcp,rxm` at a minimum to be able to use either sockets or tcp, for example.  This is another issue that's supposed to have displayed a helpful error message, but right now it is suppressed unless you turn on Mercury logging.

I'm not sure what's wrong in the second case, but I'm happy to have a look at the docker image (especially if you give me quick "how to start this image for dummies" note; it's been quite some time since I've used docker).

**Comment by MichaelBrim** [comment] 2021-02-02 22:28
@carns thanks for the info about tcp provider needing rxm. I'm fairly certain the libfabric spack package defaults to just "sockets,tcp,udp".

Before I send you my Dockerfile (with instructions), is adding the '+debug' variant to mercury spackage sufficient to get the error messages?

**Comment by MichaelBrim** [comment] 2021-02-03 15:16
@carns I found the cause for the margo_init("na+sm") failure. It seems that it initializes fine if I turn off the unifyfsd support for daemonization. Not sure why this would be problematic for margo or mercury. It is also interesting that daemonization doesn't seem to cause problems for margo_init("ofi+sockets"). I have a simple reproducer I can post, or I can submit an issue to either margo or mercury repo (I'm guessing it's likely a mercury issue).

**Comment by carns** [comment] 2021-02-03 19:37
> Before I send you my Dockerfile (with instructions), is adding the '+debug' variant to mercury spackage sufficient to get the error messages?

Ah, the variant prevents the very lowest  level of debug messages from getting compiled out altogether for performance reasons.  Unless you need those, you can leave that variant alone.

What you probably want instead is to just `export HG_LOG_LEVEL=error`.  You could also set that to warning or debug to get increasingly verbose information, but the debug ones (as mentioned above) won't activate unless you also have built with the +debug variant.

**Comment by carns** [comment] 2021-02-03 19:38
> @carns I found the cause for the margo_init("na+sm") failure. It seems that it initializes fine if I turn off the unifyfsd support for daemonization. Not sure why this would be problematic for margo or mercury. It is also interesting that daemonization doesn't seem to cause problems for margo_init("ofi+sockets"). I have a simple reproducer I can post, or I can submit an issue to either margo or mercury repo (I'm guessing it's likely a mercury issue).

That is interesting.  Agree it's likely a Mercury thing; please do open an issue there and we'll have a look at it.

**Comment by MichaelBrim** [comment] 2021-02-03 21:17
Opened an issue on mercury github for na+sm initialization failure due to daemonization.
https://github.com/mercury-hpc/mercury/issues/428

**Comment by CamStan** [comment] 2021-03-22 19:29
@MichaelBrim, do we have anything else to address on this issue? Or good to close?

**Comment by MichaelBrim** [comment] 2021-03-22 21:13
@CamStan I think it is safe to close.

**Closed** 2021-03-22 23:44 UTC
